version: '3'
services:
  cronflow:
    restart: "no"
    build: .
    volumes:
      - "./:/cronflow"
    working_dir: /cronflow
    links:
      - cronflow-db:mysql
    environment:
      - PORT=8080
      - DATABASE_DIALECT=MYSQL
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=cronflow_user
      - DATABASE_NAME=cronflow
      - DATABASE_PASSWORD=CronFlow2018!
    command: "npm run dev"
    ports:
      - "8080:8080"
  cronflow-db:
    restart: "no"
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "CronFlow2018!"
      MYSQL_DATABASE: "cronflow"
      MYSQL_USER: "cronflow_user"
      MYSQL_PASSWORD: "CronFlow2018!"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "${PWD}/local_initialization:/docker-entrypoint-initdb.d"