version: '3'
services:
  cronflow:
    restart: "no"
    build: .
    volumes:
      - "./:/cronflow"
    working_dir: /cronflow
    depends_on: 
      - cronflow-db
      - cronflow-redis
    links:
      - cronflow-db:mysql
      - cronflow-redis:redis
    environment:
      - PORT=8080
      - DATABASE_DIALECT=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=cronflow_user
      - DATABASE_NAME=cronflow
      - DATABASE_PASSWORD=CronFlow2018!
      - TOKEN_SECRET=cronflow
      - TOKEN_EXPRIED=7d
      - TOKEN_ALGORITHMS=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=cronflow
      - REDIS_DB=0
      - NPM_REGISTRY_TAOBAO=true
    command: "npm run dev"
    ports:
      - "8080:8080"
  cronflow-db:
    restart: "no"
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "CronFlow2018!"
      MYSQL_DATABASE: "cronflow"
      MYSQL_USER: "cronflow_user"
      MYSQL_PASSWORD: "CronFlow2018!"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "${PWD}/local_initialization:/docker-entrypoint-initdb.d"
  cronflow-redis:
    restart: "no"
    image: "redis:alpine"
    depends_on: 
      - cronflow-db
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "${PWD}/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"